In [3]:
import numpy as np
a1=[1,2,3,4,5,6,7,8,9,10]
a2=[11,12,13,14,15,16,17,18,19,20]
b=np.array([a1,a2])
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [4]:
b.shape


(2, 10)

In [5]:
n=np.arange(10)
n


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
import numpy as np
x=np.array([2,3,4,5,6,7,8])
x[0]

2

In [13]:
import numpy as np
x=np.array([1,2,3,4,5,6,7,8,9])
x.reshape([3,3])


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.int8

numpy.int8

In [15]:
import numpy as np
a=np.array([1,2,3,4,])
a[::2]

array([1, 3])

In [ ]:
a=np.array([1,2,3,4])

In [17]:
a.sum()

10

In [18]:
a.mean()

2.5

In [19]:
a.std()

1.118033988749895

In [20]:
a.var()

1.25

In [23]:
a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

a.sum()
a.mean()
a.var()

6.666666666666667